### Metrics
GET http://note-app.local/api/metrics

### Health Check
GET http://note-app.local/api/healthcheck

### List
GET http://note-app.local/api/notes

### Create
POST http://note-app.local/api/notes
content-type: application/json

{
    "title": "a note",
    "content": "here some reminder, mention @danangdjati",
    "is_published": true
}

### Read
GET http://note-app.local/api/notes/f1cd96ca-0515-49de-be6d-3e238748668e

### Read
GET http://note-app.local/api/cached_notes/f1cd96ca-0515-49de-be6d-3e238748668e

### Read
GET http://note-app.local/api/thunder_notes/f1cd96ca-0515-49de-be6d-3e238748668e

### Update
PATCH http://note-app.local/api/notes/f1cd96ca-0515-49de-be6d-3e238748668e
content-type: application/json

{
    "content": "here some reminder, mention @danangdjati share and like"
}

### Delete
DELETE http://note-app.local/api/notes/f1cd96ca-0515-49de-be6d-3e238748668e