apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: k6
  name: k6
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: k6
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: k6
    spec:
      containers:
        - command:
            - k6
            - run
            - /scripts/load.js
          image: grafana/k6:0.56.0
          name: k6
          ports:
            - containerPort: 6565
              protocol: TCP
          resources:
            limits:
              cpu: "5"
          volumeMounts:
            - mountPath: /scripts/load.js
              name: k6-cm0
              subPath: load.js
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: load.js
                path: load.js
            name: k6-cm0
          name: k6-cm0
