# 1. This tells docker to use the Rust official image
FROM rust:1.83 AS builder

# create a new empty shell project
WORKDIR /note-app
COPY . .
RUN cargo build --release

# our final base
# FROM debian:buster-slim
# FROM debian:bullseye
# FROM debian:bookworm-slim
FROM debian:stable-slim

# copy the build artifact from the build stage
COPY --from=builder /note-app/target/release/note-app ./note-app
COPY --from=builder /note-app/.env ./.env

USER root

ENV RUST_LOG=info
ENV RUST_BACKTRACE=full

# set the startup command to run your binary
CMD ["./note-app"]

----------------------------------------------------------
# 1. This tells docker to use the Rust official image
FROM rust:1.83 AS builder

# create a new empty shell project
RUN USER=root cargo new --bin note-app
WORKDIR /note-app

# copy over your manifests
COPY ./Cargo.lock ./Cargo.lock
COPY ./Cargo.toml ./Cargo.toml

# this build step will cache your dependencies
RUN cargo build --release && rm src/*.rs

COPY . .

# copy your source tree
# COPY ./src ./src

# build for release
# RUN rm ./target/release/deps/note-app* && cargo build --release
RUN cargo build --release

# our final base
# FROM debian:buster-slim
FROM debian:stable-slim

# copy the build artifact from the build stage
COPY --from=builder /note-app/target/release/note-app ./note-app
COPY --from=builder /note-app/.env ./.env

USER root

ENV RUST_LOG=info
ENV RUST_BACKTRACE=full

# set the startup command to run your binary
CMD ["./note-app"]
