services:

  k6:
    container_name: k6
    image: grafana/k6:0.56.0
    network_mode: host
    ports:
      - "6565:6565"
    volumes:
      - ./k6/load.js:/scripts/load.js
    deploy:
      resources:
        limits:
          cpus: '2'
    extra_hosts:
        - "note-app.local:192.168.49.2" #host and ip
    entrypoint: [ "k6", "run", "/scripts/load.js" ]
