services:
  mysql:
    image: mysql:8
    container_name: mysql
    env_file:
      - ./.env
    ports:
      - '13306:3306'
    command: --init-file /data/application/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.3'
    healthcheck:
      test: mysql ${MYSQL_DATABASE} --user=${MYSQL_USER} --password='${MYSQL_PASSWORD}' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
        - ./init_db/init.sql:/data/application/init.sql
  
  note-app:
    container_name: note-app
    image: danangdjati/note-app:1.0.0
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    deploy:
      resources:
        limits:
          cpus: '1'
    healthcheck:
      test: curl -f http://localhost:8080/api/healthcheck || exit 1
      interval: 2s
      timeout: 60s
      retries: 2
    depends_on:
      mysql:
        condition: service_healthy
  
  influxdb:
    container_name: influxdb
    image: influxdb:1.8
    ports:
      - "8186:8086"
    environment:
      - INFLUXDB_DB=k6
    deploy:
      resources:
        limits:
          cpus: '0.5'
    depends_on:
      note-app:
        condition: service_healthy

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/
    deploy:
      resources:
        limits:
          cpus: '0.5'
    depends_on:
      influxdb:
        condition: service_started

  k6:
    container_name: k6
    image: grafana/k6:latest
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://0.0.0.0:8186/k6
    volumes:
      - ./k6/load.js:/scripts/load.js
    depends_on:
      grafana:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '5'
    # command: k6 run /scripts/load.js
    # entrypoint: [ "k6", "run", "/scripts/load.js"]
    entrypoint: [ "k6", "run", "/scripts/load.js"]
    # --out influxdb=http://host.docker.internal:8186
