services:
  mysql:
    image: mysql:8
    container_name: mysql
    env_file:
      - ./.env
    ports:
      - '13306:3306'
    command: --init-file /data/application/init.sql
    volumes:
        - ./init_db/init.sql:/data/application/init.sql
  
  note-app:
    container_name: note-app
    image: danangdjati/note-app:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mysql
  
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8186"
    environment:
      - INFLUXDB_DB=k6
    depends_on:
      - note-app

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./grafana:/etc/grafana/provisioning/
    depends_on:
      - influxdb

  k6:
    image: grafana/k6:latest
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8186/k6
    volumes:
      - ./k6:/scripts
    depends_on:
      - grafana
    command: k6 run /scripts/load.js
  
