apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    tier: database
spec:
  type: NodePort
  ports:
    - name: "13306"
      port: 13306
      targetPort: 3306
      protocol: TCP
  selector:
    app: mysql
    tier: database
